In [1]:
import numpy as np
from sklearn import datasets
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn.model_selection import train_test_split
from sklearn.ensemble import VotingClassifier
import statistics as stat

In [2]:
iris = datasets.load_iris()
iris.feature_names

['sepal length (cm)',
 'sepal width (cm)',
 'petal length (cm)',
 'petal width (cm)']

In [3]:
X = iris.data[:,[0,2]]
y = iris.target

In [4]:
print(X.shape)
print(y.shape)

(150, 2)
(150,)


In [5]:
list(iris.target_names)

['setosa', 'versicolor', 'virginica']

In [6]:
X_train,X_test, y_train, y_test=train_test_split(X,y,random_state=1)

In [7]:
print(X_train.shape)
print(y_train.shape)
print(X_test.shape)
print(y_test.shape)

(112, 2)
(112,)
(38, 2)
(38,)


In [8]:
model1 = DecisionTreeClassifier(max_depth=4)
model2 = KNeighborsClassifier(n_neighbors=7)
model3 = SVC(kernel='rbf',probability=True)


In [9]:
model1.fit(X_train,y_train)
model2.fit(X_train,y_train)
model3.fit(X_train,y_train)

SVC(probability=True)

In [10]:
Score1 = model1.score(X_test,y_test)
Score1

0.9736842105263158

In [11]:
Score2 = model2.score(X_test,y_test)
Score2

0.9736842105263158

In [12]:
Score3 = model3.score(X_test,y_test)
Score3

0.9736842105263158

In [13]:
pred1 = model1.predict(X_test)
pred2 = model2.predict(X_test)
pred3 = model3.predict(X_test)

In [14]:
final_pred = np.array([])
for i in range(0,len(X_test)):
    final_pred = np.append(final_pred,stat.mode([pred1[i],
                                                pred2[i],
                                                pred3[i]]))
final_pred    

array([0., 1., 1., 0., 2., 1., 2., 0., 0., 2., 1., 0., 2., 1., 1., 0., 1.,
       1., 0., 0., 1., 1., 2., 0., 2., 1., 0., 0., 1., 2., 1., 2., 1., 2.,
       2., 0., 1., 0.])

In [15]:
total = np.sum(y_test==final_pred)
print("Accuracy:",total,"/",len(final_pred),"*100=","{0:.3f}".format(total/len(final_pred)*100),"%")

Accuracy: 37 / 38 *100= 97.368 %


In [16]:
spred1 = model1.predict_proba(X_test)
spred2 = model2.predict_proba(X_test)
spred3 = model3.predict_proba(X_test)

In [17]:
finalpred= (spred1+spred2+spred3)/3
finalpred

array([[0.98863757, 0.00571823, 0.0056442 ],
       [0.05728136, 0.93293762, 0.00978103],
       [0.00529285, 0.98503255, 0.0096746 ],
       [0.99047857, 0.00535738, 0.00416405],
       [0.00816661, 0.01435817, 0.97747522],
       [0.00430102, 0.75712364, 0.23857535],
       [0.00653685, 0.26067067, 0.73279248],
       [0.97463763, 0.02022143, 0.00514095],
       [0.98380224, 0.01148598, 0.00471178],
       [0.00404863, 0.00657775, 0.98937362],
       [0.00289818, 0.97584239, 0.02125943],
       [0.98360789, 0.01181454, 0.00457758],
       [0.00437585, 0.00535694, 0.99026722],
       [0.00413443, 0.97089705, 0.02496852],
       [0.00324469, 0.89585973, 0.10089559],
       [0.98524509, 0.00883163, 0.00592327],
       [0.00369723, 0.99163974, 0.00466303],
       [0.00346016, 0.84286706, 0.15367278],
       [0.98833732, 0.00748929, 0.0041734 ],
       [0.99090563, 0.00497057, 0.0041238 ],
       [0.00343867, 0.91939112, 0.07717021],
       [0.00374083, 0.7622502 , 0.23400896],
       [0.

In [18]:
final_classes = finalpred.argmax(axis=-1)
final_classes

array([0, 1, 1, 0, 2, 1, 2, 0, 0, 2, 1, 0, 2, 1, 1, 0, 1, 1, 0, 0, 1, 1,
       2, 0, 2, 1, 0, 0, 1, 2, 1, 2, 1, 2, 2, 0, 1, 0], dtype=int64)

In [19]:
total = np.sum([y_test[i] == final_classes[i] for i in range(len(final_classes))])
print("Accuracy:", total,"/",len(final_classes),"*100=","{0:.3f}".format(total/len(final_classes)*100),"%")

Accuracy: 37 / 38 *100= 97.368 %


In [20]:
emodel = VotingClassifier(estimators=[('dt',model1),('knn',model2),
                                     ('SVC',model3)],
                         voting= 'soft')
emodel.fit(X_train,y_train)

VotingClassifier(estimators=[('dt', DecisionTreeClassifier(max_depth=4)),
                             ('knn', KNeighborsClassifier(n_neighbors=7)),
                             ('SVC', SVC(probability=True))],
                 voting='soft')

In [21]:
escore = emodel.score(X_test,y_test)
print(escore)

0.9736842105263158


In [22]:
emodel.classes_

array([0, 1, 2])