In [1]:
import numpy as np
from sklearn import datasets
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn.model_selection import train_test_split
from sklearn.ensemble import VotingClassifier
import statistics as stat
import pandas as pd

In [2]:
URL = 'https://raw.githubusercontent.com/reddyprasade/Machine-Learning-Problems-DataSets/master/Classification/mushrooms.csv'

In [3]:
Data = pd.read_csv(URL)
Data.head()

class cap-shape cap-surface cap-color bruises odor gill-attachment  \
0     p         x           s         n       t    p               f   
1     e         x           s         y       t    a               f   
2     e         b           s         w       t    l               f   
3     p         x           y         w       t    p               f   
4     e         x           s         g       f    n               f   

  gill-spacing gill-size gill-color  ... stalk-surface-below-ring  \
0            c         n          k  ...                        s   
1            c         b          k  ...                        s   
2            c         b          n  ...                        s   
3            c         n          n  ...                        s   
4            w         b          k  ...                        s   

  stalk-color-above-ring stalk-color-below-ring veil-type veil-color  \
0                      w                      w         p          w   
1                      w                      w         p          w   
2                      w                      w         p          w   
3                      w                      w         p          w   
4                      w                      w         p          w   

  ring-number ring-type spore-print-color population habitat  
0           o         p                 k          s       u  
1           o         p                 n          n       g  
2           o         p                 n          n       m  
3           o         p                 k          s       u  
4           o         e                 n          a       g  

[5 rows x 23 columns]

In [4]:
Data.tail()

class cap-shape cap-surface cap-color bruises odor gill-attachment  \
8119     e         k           s         n       f    n               a   
8120     e         x           s         n       f    n               a   
8121     e         f           s         n       f    n               a   
8122     p         k           y         n       f    y               f   
8123     e         x           s         n       f    n               a   

     gill-spacing gill-size gill-color  ... stalk-surface-below-ring  \
8119            c         b          y  ...                        s   
8120            c         b          y  ...                        s   
8121            c         b          n  ...                        s   
8122            c         n          b  ...                        k   
8123            c         b          y  ...                        s   

     stalk-color-above-ring stalk-color-below-ring veil-type veil-color  \
8119                      o                      o         p          o   
8120                      o                      o         p          n   
8121                      o                      o         p          o   
8122                      w                      w         p          w   
8123                      o                      o         p          o   

     ring-number ring-type spore-print-color population habitat  
8119           o         p                 b          c       l  
8120           o         p                 b          v       l  
8121           o         p                 b          c       l  
8122           o         e                 w          v       l  
8123           o         p                 o          c       l  

[5 rows x 23 columns]

In [5]:
Data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8124 entries, 0 to 8123
Data columns (total 23 columns):
 #   Column                    Non-Null Count  Dtype 
---  ------                    --------------  ----- 
 0   class                     8124 non-null   object
 1   cap-shape                 8124 non-null   object
 2   cap-surface               8124 non-null   object
 3   cap-color                 8124 non-null   object
 4   bruises                   8124 non-null   object
 5   odor                      8124 non-null   object
 6   gill-attachment           8124 non-null   object
 7   gill-spacing              8124 non-null   object
 8   gill-size                 8124 non-null   object
 9   gill-color                8124 non-null   object
 10  stalk-shape               8124 non-null   object
 11  stalk-root                8124 non-null   object
 12  stalk-surface-above-ring  8124 non-null   object
 13  stalk-surface-below-ring  8124 non-null   object
 14  stalk-color-above-ring  

In [6]:
Data.describe()

class cap-shape cap-surface cap-color bruises  odor gill-attachment  \
count   8124      8124        8124      8124    8124  8124            8124   
unique     2         6           4        10       2     9               2   
top        e         x           y         n       f     n               f   
freq    4208      3656        3244      2284    4748  3528            7914   

       gill-spacing gill-size gill-color  ... stalk-surface-below-ring  \
count          8124      8124       8124  ...                     8124   
unique            2         2         12  ...                        4   
top               c         b          b  ...                        s   
freq           6812      5612       1728  ...                     4936   

       stalk-color-above-ring stalk-color-below-ring veil-type veil-color  \
count                    8124                   8124      8124       8124   
unique                      9                      9         1          4   
top                         w                      w         p          w   
freq                     4464                   4384      8124       7924   

       ring-number ring-type spore-print-color population habitat  
count         8124      8124              8124       8124    8124  
unique           3         5                 9          6       7  
top              o         p                 w          v       d  
freq          7488      3968              2388       4040    3148  

[4 rows x 23 columns]

In [7]:
Data_encode = pd.get_dummies(Data)
Data_encode

class_e  class_p  cap-shape_b  cap-shape_c  cap-shape_f  cap-shape_k  \
0           0        1            0            0            0            0   
1           1        0            0            0            0            0   
2           1        0            1            0            0            0   
3           0        1            0            0            0            0   
4           1        0            0            0            0            0   
...       ...      ...          ...          ...          ...          ...   
8119        1        0            0            0            0            1   
8120        1        0            0            0            0            0   
8121        1        0            0            0            1            0   
8122        0        1            0            0            0            1   
8123        1        0            0            0            0            0   

      cap-shape_s  cap-shape_x  cap-surface_f  cap-surface_g  ...  \
0               0            1              0              0  ...   
1               0            1              0              0  ...   
2               0            0              0              0  ...   
3               0            1              0              0  ...   
4               0            1              0              0  ...   
...           ...          ...            ...            ...  ...   
8119            0            0              0              0  ...   
8120            0            1              0              0  ...   
8121            0            0              0              0  ...   
8122            0            0              0              0  ...   
8123            0            1              0              0  ...   

      population_s  population_v  population_y  habitat_d  habitat_g  \
0                1             0             0          0          0   
1                0             0             0          0          1   
2                0             0             0          0          0   
3                1             0             0          0          0   
4                0             0             0          0          1   
...            ...           ...           ...        ...        ...   
8119             0             0             0          0          0   
8120             0             1             0          0          0   
8121             0             0             0          0          0   
8122             0             1             0          0          0   
8123             0             0             0          0          0   

      habitat_l  habitat_m  habitat_p  habitat_u  habitat_w  
0             0          0          0          1          0  
1             0          0          0          0          0  
2             0          1          0          0          0  
3             0          0          0          1          0  
4             0          0          0          0          0  
...         ...        ...        ...        ...        ...  
8119          1          0          0          0          0  
8120          1          0          0          0          0  
8121          1          0          0          0          0  
8122          1          0          0          0          0  
8123          1          0          0          0          0  

[8124 rows x 119 columns]

In [8]:
X_mush = Data_encode.iloc[:,2:]
y_mush = Data_encode.iloc[:,1]
X_mush

cap-shape_b  cap-shape_c  cap-shape_f  cap-shape_k  cap-shape_s  \
0               0            0            0            0            0   
1               0            0            0            0            0   
2               1            0            0            0            0   
3               0            0            0            0            0   
4               0            0            0            0            0   
...           ...          ...          ...          ...          ...   
8119            0            0            0            1            0   
8120            0            0            0            0            0   
8121            0            0            1            0            0   
8122            0            0            0            1            0   
8123            0            0            0            0            0   

      cap-shape_x  cap-surface_f  cap-surface_g  cap-surface_s  cap-surface_y  \
0               1              0              0              1              0   
1               1              0              0              1              0   
2               0              0              0              1              0   
3               1              0              0              0              1   
4               1              0              0              1              0   
...           ...            ...            ...            ...            ...   
8119            0              0              0              1              0   
8120            1              0              0              1              0   
8121            0              0              0              1              0   
8122            0              0              0              0              1   
8123            1              0              0              1              0   

      ...  population_s  population_v  population_y  habitat_d  habitat_g  \
0     ...             1             0             0          0          0   
1     ...             0             0             0          0          1   
2     ...             0             0             0          0          0   
3     ...             1             0             0          0          0   
4     ...             0             0             0          0          1   
...   ...           ...           ...           ...        ...        ...   
8119  ...             0             0             0          0          0   
8120  ...             0             1             0          0          0   
8121  ...             0             0             0          0          0   
8122  ...             0             1             0          0          0   
8123  ...             0             0             0          0          0   

      habitat_l  habitat_m  habitat_p  habitat_u  habitat_w  
0             0          0          0          1          0  
1             0          0          0          0          0  
2             0          1          0          0          0  
3             0          0          0          1          0  
4             0          0          0          0          0  
...         ...        ...        ...        ...        ...  
8119          1          0          0          0          0  
8120          1          0          0          0          0  
8121          1          0          0          0          0  
8122          1          0          0          0          0  
8123          1          0          0          0          0  

[8124 rows x 117 columns]

In [9]:
y_mush

0       1
1       0
2       0
3       1
4       0
       ..
8119    0
8120    0
8121    0
8122    1
8123    0
Name: class_p, Length: 8124, dtype: uint8

In [10]:
X_train,X_test, y_train, y_test=train_test_split(X_mush,y_mush,random_state=1)

In [11]:
print(X_train.shape)
print(y_train.shape)
print(X_test.shape)
print(y_test.shape)

(6093, 117)
(6093,)
(2031, 117)
(2031,)


In [12]:
model1 = DecisionTreeClassifier(max_depth=4)
model2 = KNeighborsClassifier(n_neighbors=7)
model3 = SVC(kernel='rbf',probability=True)

In [13]:
model1.fit(X_train,y_train)
model2.fit(X_train,y_train)
model3.fit(X_train,y_train)

SVC(probability=True)

In [14]:
Score1 = model1.score(X_test,y_test)
Score1

0.9852289512555391

In [15]:
Score2 = model2.score(X_test,y_test)
Score2

0.9985228951255539

In [16]:
Score3 = model3.score(X_test,y_test)
Score3

1.0

In [17]:
pred1 = model1.predict(X_test)
pred2 = model2.predict(X_test)
pred3 = model3.predict(X_test)

In [18]:
final_pred = np.array([])
for i in range(0,len(X_test)):
    final_pred = np.append(final_pred,stat.mode([pred1[i],
                                                pred2[i],
                                                pred3[i]]))
final_pred    

array([0., 1., 1., ..., 1., 1., 1.])

In [19]:
total = np.sum(y_test==final_pred)
print("Accuracy:",total,"/",len(final_pred),"*100=","{0:.3f}".format(total/len(final_pred)*100),"%")

Accuracy: 2029 / 2031 *100= 99.902 %


In [20]:
spred1 = model1.predict_proba(X_test)
spred2 = model2.predict_proba(X_test)
spred3 = model3.predict_proba(X_test)

In [21]:
finalpred= (spred1+spred2+spred3)/3
finalpred

array([[9.99413898e-01, 5.86102449e-04],
       [1.80827909e-01, 8.19172091e-01],
       [1.80827908e-01, 8.19172092e-01],
       ...,
       [2.24571039e-08, 9.99999978e-01],
       [1.16279428e-08, 9.99999988e-01],
       [7.15864727e-10, 9.99999999e-01]])

In [22]:
final_classes = finalpred.argmax(axis=-1)
final_classes

array([0, 1, 1, ..., 1, 1, 1], dtype=int64)

In [23]:
total = np.sum([y_test == final_classes[i] for i in range(len(final_classes))])
print("Accuracy:", total,"/",len(final_classes),"*100=","{0:.3f}".format(total/len(final_classes)*100),"%")

Accuracy: 2062548 / 2031 *100= 101553.323 %


In [24]:
final_classes[i]

1

In [25]:
total

2062548

In [26]:
len(final_classes)

2031

In [27]:
emodel = VotingClassifier(estimators=[('dt',model1),('knn',model2),
                                     ('SVC',model3)],
                         voting= 'soft')
emodel.fit(X_train,y_train)

VotingClassifier(estimators=[('dt', DecisionTreeClassifier(max_depth=4)),
                             ('knn', KNeighborsClassifier(n_neighbors=7)),
                             ('SVC', SVC(probability=True))],
                 voting='soft')

In [28]:
escore = emodel.score(X_test,y_test)
print(escore)

0.999507631708518


In [29]:
emodel.classes_

array([0, 1], dtype=uint8)