In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
import pandas_profiling

In [3]:
URL = 'https://raw.githubusercontent.com/reddyprasade/Machine-Learning-Problems-DataSets/master/Classification/ChurnData.csv'

In [4]:
churn_df = pd.read_csv(URL)
churn_df.head()

tenure   age  address  income   ed  employ  equip  callcard  wireless  \
0    11.0  33.0      7.0   136.0  5.0     5.0    0.0       1.0       1.0   
1    33.0  33.0     12.0    33.0  2.0     0.0    0.0       0.0       0.0   
2    23.0  30.0      9.0    30.0  1.0     2.0    0.0       0.0       0.0   
3    38.0  35.0      5.0    76.0  2.0    10.0    1.0       1.0       1.0   
4     7.0  35.0     14.0    80.0  2.0    15.0    0.0       1.0       0.0   

   longmon  ...  pager  internet  callwait  confer  ebill  loglong  logtoll  \
0     4.40  ...    1.0       0.0       1.0     1.0    0.0    1.482    3.033   
1     9.45  ...    0.0       0.0       0.0     0.0    0.0    2.246    3.240   
2     6.30  ...    0.0       0.0       0.0     1.0    0.0    1.841    3.240   
3     6.05  ...    1.0       1.0       1.0     1.0    1.0    1.800    3.807   
4     7.10  ...    0.0       0.0       1.0     1.0    0.0    1.960    3.091   

   lninc  custcat  churn  
0  4.913      4.0    1.0  
1  3.497      1.0    1.0  
2  3.401      3.0    0.0  
3  4.331      4.0    0.0  
4  4.382      3.0    0.0  

[5 rows x 28 columns]

In [5]:
churn_df.tail()

tenure   age  address  income   ed  employ  equip  callcard  wireless  \
195    55.0  44.0     24.0    83.0  1.0    23.0    0.0       1.0       0.0   
196    34.0  23.0      3.0    24.0  1.0     7.0    0.0       1.0       0.0   
197     6.0  32.0     10.0    47.0  1.0    10.0    0.0       1.0       0.0   
198    24.0  30.0      0.0    25.0  4.0     5.0    0.0       1.0       1.0   
199    61.0  50.0     16.0   190.0  2.0    22.0    1.0       1.0       1.0   

     longmon  ...  pager  internet  callwait  confer  ebill  loglong  logtoll  \
195    17.35  ...    0.0       0.0       0.0     1.0    0.0    2.854    3.199   
196     6.00  ...    0.0       0.0       1.0     1.0    0.0    1.792    3.332   
197     3.85  ...    0.0       0.0       1.0     1.0    0.0    1.348    3.168   
198     8.70  ...    1.0       1.0       1.0     1.0    1.0    2.163    3.866   
199    16.85  ...    0.0       1.0       0.0     0.0    1.0    2.824    3.240   

     lninc  custcat  churn  
195  4.419      3.0    0.0  
196  3.178      3.0    0.0  
197  3.850      3.0    0.0  
198  3.219      4.0    1.0  
199  5.247      2.0    0.0  

[5 rows x 28 columns]

In [6]:
churn_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 28 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   tenure    200 non-null    float64
 1   age       200 non-null    float64
 2   address   200 non-null    float64
 3   income    200 non-null    float64
 4   ed        200 non-null    float64
 5   employ    200 non-null    float64
 6   equip     200 non-null    float64
 7   callcard  200 non-null    float64
 8   wireless  200 non-null    float64
 9   longmon   200 non-null    float64
 10  tollmon   200 non-null    float64
 11  equipmon  200 non-null    float64
 12  cardmon   200 non-null    float64
 13  wiremon   200 non-null    float64
 14  longten   200 non-null    float64
 15  tollten   200 non-null    float64
 16  cardten   200 non-null    float64
 17  voice     200 non-null    float64
 18  pager     200 non-null    float64
 19  internet  200 non-null    float64
 20  callwait  200 non-null    float6

In [7]:
churn_df.isna().sum()

tenure      0
age         0
address     0
income      0
ed          0
employ      0
equip       0
callcard    0
wireless    0
longmon     0
tollmon     0
equipmon    0
cardmon     0
wiremon     0
longten     0
tollten     0
cardten     0
voice       0
pager       0
internet    0
callwait    0
confer      0
ebill       0
loglong     0
logtoll     0
lninc       0
custcat     0
churn       0
dtype: int64

In [8]:
churn_df.columns

Index(['tenure', 'age', 'address', 'income', 'ed', 'employ', 'equip',
       'callcard', 'wireless', 'longmon', 'tollmon', 'equipmon', 'cardmon',
       'wiremon', 'longten', 'tollten', 'cardten', 'voice', 'pager',
       'internet', 'callwait', 'confer', 'ebill', 'loglong', 'logtoll',
       'lninc', 'custcat', 'churn'],
      dtype='object')

In [9]:
churn_df = churn_df[['tenure', 'age', 'address', 'income', 'ed', 'employ', 'equip',
       'callcard', 'wireless','churn']]

In [10]:
churn_df.head()

tenure   age  address  income   ed  employ  equip  callcard  wireless  \
0    11.0  33.0      7.0   136.0  5.0     5.0    0.0       1.0       1.0   
1    33.0  33.0     12.0    33.0  2.0     0.0    0.0       0.0       0.0   
2    23.0  30.0      9.0    30.0  1.0     2.0    0.0       0.0       0.0   
3    38.0  35.0      5.0    76.0  2.0    10.0    1.0       1.0       1.0   
4     7.0  35.0     14.0    80.0  2.0    15.0    0.0       1.0       0.0   

   churn  
0    1.0  
1    1.0  
2    0.0  
3    0.0  
4    0.0

In [11]:
churn_df['churn'] = churn_df['churn'].astype('int')

In [12]:
churn_df

tenure   age  address  income   ed  employ  equip  callcard  wireless  \
0      11.0  33.0      7.0   136.0  5.0     5.0    0.0       1.0       1.0   
1      33.0  33.0     12.0    33.0  2.0     0.0    0.0       0.0       0.0   
2      23.0  30.0      9.0    30.0  1.0     2.0    0.0       0.0       0.0   
3      38.0  35.0      5.0    76.0  2.0    10.0    1.0       1.0       1.0   
4       7.0  35.0     14.0    80.0  2.0    15.0    0.0       1.0       0.0   
..      ...   ...      ...     ...  ...     ...    ...       ...       ...   
195    55.0  44.0     24.0    83.0  1.0    23.0    0.0       1.0       0.0   
196    34.0  23.0      3.0    24.0  1.0     7.0    0.0       1.0       0.0   
197     6.0  32.0     10.0    47.0  1.0    10.0    0.0       1.0       0.0   
198    24.0  30.0      0.0    25.0  4.0     5.0    0.0       1.0       1.0   
199    61.0  50.0     16.0   190.0  2.0    22.0    1.0       1.0       1.0   

     churn  
0        1  
1        1  
2        0  
3        0  
4        0  
..     ...  
195      0  
196      0  
197      0  
198      1  
199      0  

[200 rows x 10 columns]

In [13]:
churn_df.isna().any()

tenure      False
age         False
address     False
income      False
ed          False
employ      False
equip       False
callcard    False
wireless    False
churn       False
dtype: bool

In [14]:
X = np.asarray(churn_df[['tenure', 'age', 'address', 'income', 'ed', 'employ', 'equip']])
X[0:5]

array([[ 11.,  33.,   7., 136.,   5.,   5.,   0.],
       [ 33.,  33.,  12.,  33.,   2.,   0.,   0.],
       [ 23.,  30.,   9.,  30.,   1.,   2.,   0.],
       [ 38.,  35.,   5.,  76.,   2.,  10.,   1.],
       [  7.,  35.,  14.,  80.,   2.,  15.,   0.]])

In [15]:
y = np.asarray(churn_df['churn'])

In [16]:
y[0:5]

array([1, 1, 0, 0, 0])

In [17]:
from sklearn import preprocessing
X = preprocessing.StandardScaler().fit(X).transform(X)
X[0:5]

array([[-1.13518441, -0.62595491, -0.4588971 ,  0.4751423 ,  1.6961288 ,
        -0.58477841, -0.85972695],
       [-0.11604313, -0.62595491,  0.03454064, -0.32886061, -0.6433592 ,
        -1.14437497, -0.85972695],
       [-0.57928917, -0.85594447, -0.261522  , -0.35227817, -1.42318853,
        -0.92053635, -0.85972695],
       [ 0.11557989, -0.47262854, -0.65627219,  0.00679109, -0.6433592 ,
        -0.02518185,  1.16316   ],
       [-1.32048283, -0.47262854,  0.23191574,  0.03801451, -0.6433592 ,
         0.53441472, -0.85972695]])

In [18]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y)
print('Train set:', X_train.shape, y_train.shape)
print('Test set:', X_test.shape, y_test.shape)

Train set: (150, 7) (150,)
Test set: (50, 7) (50,)


In [19]:
X_train

array([[ 0.16190449, -0.54929173, -0.75495974, ...,  1.6961288 ,
        -0.80861704,  1.16316   ],
       [-0.06971853, -0.08931261,  0.92272857, ...,  0.91629947,
        -0.13710116,  1.16316   ],
       [-0.48663996, -0.85594447, -1.14970993, ..., -1.42318853,
        -0.69669772, -0.85972695],
       ...,
       [ 0.81044894, -1.46924996, -1.05102238, ...,  0.91629947,
        -1.14437497,  1.16316   ],
       [-0.71826298, -0.7026181 , -0.16283445, ...,  0.13647013,
        -0.58477841,  1.16316   ],
       [ 1.04207196,  1.29062473, -0.16283445, ..., -0.6433592 ,
         0.75825334, -0.85972695]])

In [20]:
X_test

array([[-1.36680743, -0.7026181 , -0.16283445, -0.21957866, -1.42318853,
        -0.02518185, -0.85972695],
       [-1.08885981, -1.31592358, -0.95233483, -0.43814256, -1.42318853,
        -1.14437497, -0.85972695],
       [-1.41313204, -0.85594447, -0.85364729, -0.22738451,  0.91629947,
        -0.36093978,  1.16316   ],
       [ 1.69061641,  2.59389889,  2.50172933, -0.32886061, -1.42318853,
         3.78007479, -0.85972695],
       [ 1.4589934 , -0.08931261,  0.23191574, -0.12590842,  0.13647013,
         0.08673747, -0.85972695],
       [-1.32048283, -0.47262854,  0.23191574,  0.03801451, -0.6433592 ,
         0.53441472, -0.85972695],
       [ 1.13472117,  1.13729836,  0.72535348, -0.18835524,  0.91629947,
         0.08673747,  1.16316   ],
       [ 0.16190449,  0.44732969, -1.05102238, -0.05565574,  0.91629947,
        -0.02518185, -0.85972695],
       [ 0.94942275,  0.06401376, -0.16283445, -0.39911329, -0.6433592 ,
        -0.58477841, -0.85972695],
       [-1.22783362, -0.0893

In [48]:
from sklearn.linear_model import LogisticRegression

In [49]:
Lr = LogisticRegression(solver='newton-cg',C=1.0,max_iter=100)

In [50]:
Lr.fit(X_train,y_train)

LogisticRegression(solver='newton-cg')

In [51]:
Lr.coef_

array([[-0.70832631, -0.11059339,  0.06182996, -0.07652586,  0.39080894,
        -0.51854111,  0.39809391]])

In [52]:
Lr.intercept_

array([-1.20124445])

In [53]:
Training_score = Lr.score(X_train,y_train)

In [54]:
print(Training_score)

0.7666666666666667


In [55]:
new_prediction = Lr.predict(X_test)

In [56]:
Test_score = Lr.score(X_test, new_prediction)

In [57]:
print(Test_score)

1.0


In [58]:
pd.DataFrame({'ActualData': y_test,
             'New_predicted_data': new_prediction})

ActualData  New_predicted_data
0            0                   0
1            1                   0
2            1                   1
3            0                   0
4            0                   0
5            0                   0
6            0                   0
7            1                   0
8            0                   0
9            1                   1
10           0                   0
11           0                   0
12           1                   1
13           0                   0
14           0                   0
15           1                   1
16           0                   0
17           1                   0
18           0                   0
19           1                   0
20           0                   0
21           0                   0
22           1                   1
23           0                   0
24           0                   0
25           0                   0
26           0                   0
27           1                   1
28           0                   0
29           0                   0
30           0                   0
31           0                   0
32           0                   0
33           0                   0
34           0                   0
35           0                   0
36           1                   0
37           0                   0
38           0                   0
39           0                   0
40           1                   0
41           0                   1
42           0                   1
43           0                   0
44           1                   0
45           0                   0
46           0                   0
47           0                   0
48           0                   1
49           0                   0

In [59]:
print('Predicted_Probability', Lr.predict_proba(X_test))

Predicted_Probability [[0.73769984 0.26230016]
 [0.64904384 0.35095616]
 [0.29581584 0.70418416]
 [0.99534127 0.00465873]
 [0.92654102 0.07345898]
 [0.745169   0.254831  ]
 [0.78505041 0.21494959]
 [0.80174224 0.19825776]
 [0.89574366 0.10425634]
 [0.32803985 0.67196015]
 [0.97876502 0.02123498]
 [0.68442998 0.31557002]
 [0.48169872 0.51830128]
 [0.76855527 0.23144473]
 [0.60935886 0.39064114]
 [0.28910821 0.71089179]
 [0.77056415 0.22943585]
 [0.54203749 0.45796251]
 [0.81233692 0.18766308]
 [0.59891176 0.40108824]
 [0.92587304 0.07412696]
 [0.73999435 0.26000565]
 [0.22597997 0.77402003]
 [0.89655629 0.10344371]
 [0.95254493 0.04745507]
 [0.52770909 0.47229091]
 [0.76707751 0.23292249]
 [0.23489729 0.76510271]
 [0.79446308 0.20553692]
 [0.9471421  0.0528579 ]
 [0.95253417 0.04746583]
 [0.5363139  0.4636861 ]
 [0.85543649 0.14456351]
 [0.69659973 0.30340027]
 [0.82839718 0.17160282]
 [0.74447138 0.25552862]
 [0.86394262 0.13605738]
 [0.92858639 0.07141361]
 [0.96800501 0.03199499]
 [0

In [60]:
from sklearn.metrics import jaccard_score

In [61]:
jaccard_score(y_test,new_prediction)

0.375

In [62]:
{0,2,5} 

{0,1,2,3,4,5,6,7,8,9}

{0, 1, 2, 3, 4, 5, 6, 7, 8, 9}

In [63]:
from sklearn.metrics import confusion_matrix 

In [64]:
cm  = confusion_matrix(y_test, new_prediction)

In [65]:
print(cm)

[[34  3]
 [ 7  6]]


In [66]:
True_positive = cm[0,0]
True_positive

34

In [67]:
False_negative = cm[0,1]
False_negative

3

In [68]:
False_positive = cm[1,0]
False_positive

7

In [69]:
True_negative = cm[1,1]
True_negative

6

In [70]:
prediction_error = False_positive + False_negative /False_positive + False_negative + True_positive + True_negative

In [71]:
print(prediction_error)

50.42857142857143


In [72]:
Accuracy_model = True_positive + True_negative / False_positive + False_negative + True_positive + True_negative

In [73]:
Accuracy_model

77.85714285714286

In [76]:
Overall_model_correction = (0.375*100) + 50.42857142857143
Overall_model_correction

87.92857142857143

In [77]:
X_train == X_train

array([[ True,  True,  True, ...,  True,  True,  True],
       [ True,  True,  True, ...,  True,  True,  True],
       [ True,  True,  True, ...,  True,  True,  True],
       ...,
       [ True,  True,  True, ...,  True,  True,  True],
       [ True,  True,  True, ...,  True,  True,  True],
       [ True,  True,  True, ...,  True,  True,  True]])