In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [12]:
Boston = pd.read_csv("https://raw.githubusercontent.com/reddyprasade/Machine-Learning-Problems-DataSets/master/Regression/00%20Boston%20Housing%20dataset/housing.csv",header=None)

In [13]:
Boston.head()

0     1     2   3      4      5     6       7   8      9     10  \
0  0.00632  18.0  2.31   0  0.538  6.575  65.2  4.0900   1  296.0  15.3   
1  0.02731   0.0  7.07   0  0.469  6.421  78.9  4.9671   2  242.0  17.8   
2  0.02729   0.0  7.07   0  0.469  7.185  61.1  4.9671   2  242.0  17.8   
3  0.03237   0.0  2.18   0  0.458  6.998  45.8  6.0622   3  222.0  18.7   
4  0.06905   0.0  2.18   0  0.458  7.147  54.2  6.0622   3  222.0  18.7   

       11    12    13  
0  396.90  4.98  24.0  
1  396.90  9.14  21.6  
2  392.83  4.03  34.7  
3  394.63  2.94  33.4  
4  396.90  5.33  36.2

In [21]:
Names = ['CRIM', 'ZN', 'INDUS','CHAS','NOX','RM','AGE','DIS','RAD','TAX','PTRATIO','B','LSTAT','Price']

In [22]:
Boston.columns=Names

In [23]:
Boston.head()

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0  0.00632  18.0   2.31     0  0.538  6.575  65.2  4.0900    1  296.0   
1  0.02731   0.0   7.07     0  0.469  6.421  78.9  4.9671    2  242.0   
2  0.02729   0.0   7.07     0  0.469  7.185  61.1  4.9671    2  242.0   
3  0.03237   0.0   2.18     0  0.458  6.998  45.8  6.0622    3  222.0   
4  0.06905   0.0   2.18     0  0.458  7.147  54.2  6.0622    3  222.0   

   PTRATIO       B  LSTAT  Price  
0     15.3  396.90   4.98   24.0  
1     17.8  396.90   9.14   21.6  
2     17.8  392.83   4.03   34.7  
3     18.7  394.63   2.94   33.4  
4     18.7  396.90   5.33   36.2

In [24]:
Boston.tail()

CRIM   ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
501  0.06263  0.0  11.93     0  0.573  6.593  69.1  2.4786    1  273.0   
502  0.04527  0.0  11.93     0  0.573  6.120  76.7  2.2875    1  273.0   
503  0.06076  0.0  11.93     0  0.573  6.976  91.0  2.1675    1  273.0   
504  0.10959  0.0  11.93     0  0.573  6.794  89.3  2.3889    1  273.0   
505  0.04741  0.0  11.93     0  0.573  6.030  80.8  2.5050    1  273.0   

     PTRATIO       B  LSTAT  Price  
501     21.0  391.99   9.67   22.4  
502     21.0  396.90   9.08   20.6  
503     21.0  396.90   5.64   23.9  
504     21.0  393.45   6.48   22.0  
505     21.0  396.90   7.88   11.9

In [25]:
Boston.describe()

CRIM          ZN       INDUS        CHAS         NOX          RM  \
count  506.000000  506.000000  506.000000  506.000000  506.000000  506.000000   
mean     3.613524   11.363636   11.136779    0.069170    0.554695    6.284634   
std      8.601545   23.322453    6.860353    0.253994    0.115878    0.702617   
min      0.006320    0.000000    0.460000    0.000000    0.385000    3.561000   
25%      0.082045    0.000000    5.190000    0.000000    0.449000    5.885500   
50%      0.256510    0.000000    9.690000    0.000000    0.538000    6.208500   
75%      3.677082   12.500000   18.100000    0.000000    0.624000    6.623500   
max     88.976200  100.000000   27.740000    1.000000    0.871000    8.780000   

              AGE         DIS         RAD         TAX     PTRATIO           B  \
count  506.000000  506.000000  506.000000  506.000000  506.000000  506.000000   
mean    68.574901    3.795043    9.549407  408.237154   18.455534  356.674032   
std     28.148861    2.105710    8.707259  168.537116    2.164946   91.294864   
min      2.900000    1.129600    1.000000  187.000000   12.600000    0.320000   
25%     45.025000    2.100175    4.000000  279.000000   17.400000  375.377500   
50%     77.500000    3.207450    5.000000  330.000000   19.050000  391.440000   
75%     94.075000    5.188425   24.000000  666.000000   20.200000  396.225000   
max    100.000000   12.126500   24.000000  711.000000   22.000000  396.900000   

            LSTAT       Price  
count  506.000000  506.000000  
mean    12.653063   22.532806  
std      7.141062    9.197104  
min      1.730000    5.000000  
25%      6.950000   17.025000  
50%     11.360000   21.200000  
75%     16.955000   25.000000  
max     37.970000   50.000000

In [31]:
Boston.isna().sum()

CRIM       0
ZN         0
INDUS      0
CHAS       0
NOX        0
RM         0
AGE        0
DIS        0
RAD        0
TAX        0
PTRATIO    0
B          0
LSTAT      0
Price      0
dtype: int64

In [32]:
Features = Boston.drop('Price',axis=1)
Features.head()

CRIM    ZN  INDUS  CHAS    NOX     RM   AGE     DIS  RAD    TAX  \
0  0.00632  18.0   2.31     0  0.538  6.575  65.2  4.0900    1  296.0   
1  0.02731   0.0   7.07     0  0.469  6.421  78.9  4.9671    2  242.0   
2  0.02729   0.0   7.07     0  0.469  7.185  61.1  4.9671    2  242.0   
3  0.03237   0.0   2.18     0  0.458  6.998  45.8  6.0622    3  222.0   
4  0.06905   0.0   2.18     0  0.458  7.147  54.2  6.0622    3  222.0   

   PTRATIO       B  LSTAT  
0     15.3  396.90   4.98  
1     17.8  396.90   9.14  
2     17.8  392.83   4.03  
3     18.7  394.63   2.94  
4     18.7  396.90   5.33

In [33]:
Target = Boston['Price']
Target

0      24.0
1      21.6
2      34.7
3      33.4
4      36.2
       ... 
501    22.4
502    20.6
503    23.9
504    22.0
505    11.9
Name: Price, Length: 506, dtype: float64

In [69]:
from sklearn import linear_model
from sklearn.metrics import mean_squared_error

In [70]:
X_train1=Features[:300]
X_train2=Features[300:500]
X_test=Features[500:]

In [71]:
y_train1=Target[:300]
y_train2=Target[300:500]
y_test=Target[500:]

In [72]:
model1 = linear_model.LinearRegression()
model2 = linear_model.LinearRegression()
model1.fit(X_train1,y_train1)
model2.fit(X_train2,y_train2)

pred1=model1.predict(X_test)
pred2=model2.predict(X_test)

finalpred=(pred1+pred2)/2
finalpred

array([19.95606901, 23.29878597, 21.95728211, 26.83576744, 25.43892452,
       21.7536474 ])

In [73]:
model1 = linear_model.LassoCV()
model2 = linear_model.LassoCV()
model1.fit(X_train1,y_train1)
model2.fit(X_train2,y_train2)

pred1=model1.predict(X_test)
pred2=model2.predict(X_test)

finalpred=(pred1+pred2)/2
finalpred

array([20.12045588, 24.87137331, 23.33250614, 28.4588172 , 27.08513434,
       23.30195426])

In [74]:
print("Train score of First model is",model1.score(X_train1,y_train1))
print("Train score of Second model is",model2.score(X_train2,y_train2))
print('*'*30)
print("Test score of First model is",model1.score(X_test,pred1))
print("Test score of First model is",model1.score(X_test,pred2))


Train score of First model is 0.870422464151611
Train score of Second model is 0.6021855154490381
******************************
Test score of First model is 1.0
Test score of First model is -0.034207280789770866


In [55]:
print("Train score of First model is",model1.score(X_train1,y_train1))
print("Train score of Second model is",model2.score(X_train2,y_train2))
print('*'*30)
print("Test score of First model is",model1.score(X_test,pred1))
print("Test score of First model is",model1.score(X_test,pred2))


Train score of First model is 0.870422464151611
Train score of Second model is 0.6021855154490381
******************************
Test score of First model is 1.0
Test score of First model is -0.034207280789770866


In [75]:
finalpred=(pred1+pred2)/2
finalpred

array([20.12045588, 24.87137331, 23.33250614, 28.4588172 , 27.08513434,
       23.30195426])

In [76]:
y_test.shape

(6,)

In [77]:
finalpred.shape

(6,)

In [78]:
print(mean_squared_error(y_test, finalpred, sample_weight=None, multioutput='uniform_average'))

33.540944947648384


In [79]:
from sklearn.metrics import mean_squared_error,r2_score

In [80]:
mean_squared_error(y_test,finalpred)

33.540944947648384

In [81]:
r2_score(y_test,finalpred)

-1.0080390110346276

In [82]:
model1.score(X_train1,y_train1)

0.870422464151611

In [83]:
model1.score(X_test,y_test)

-0.990511791243226

In [84]:
model2.score(X_train2,y_train2)

0.6021855154490381

In [85]:
model2.score(X_test,y_test)

-1.1888985830641685