In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
URL = 'https://raw.githubusercontent.com/reddyprasade/Machine-Learning-Problems-DataSets/master/Classification/fruit_data_with_colors.txt'

In [3]:
Data = pd.read_table(URL)
Data.head()

fruit_label fruit_name fruit_subtype  mass  width  height  color_score
0            1      apple  granny_smith   192    8.4     7.3         0.55
1            1      apple  granny_smith   180    8.0     6.8         0.59
2            1      apple  granny_smith   176    7.4     7.2         0.60
3            2   mandarin      mandarin    86    6.2     4.7         0.80
4            2   mandarin      mandarin    84    6.0     4.6         0.79

In [4]:
Data.tail()

fruit_label fruit_name fruit_subtype  mass  width  height  color_score
54            4      lemon       unknown   116    6.1     8.5         0.71
55            4      lemon       unknown   116    6.3     7.7         0.72
56            4      lemon       unknown   116    5.9     8.1         0.73
57            4      lemon       unknown   152    6.5     8.5         0.72
58            4      lemon       unknown   118    6.1     8.1         0.70

In [5]:
Data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 59 entries, 0 to 58
Data columns (total 7 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   fruit_label    59 non-null     int64  
 1   fruit_name     59 non-null     object 
 2   fruit_subtype  59 non-null     object 
 3   mass           59 non-null     int64  
 4   width          59 non-null     float64
 5   height         59 non-null     float64
 6   color_score    59 non-null     float64
dtypes: float64(3), int64(2), object(2)
memory usage: 3.4+ KB


In [6]:
from sklearn.preprocessing import LabelEncoder

In [7]:
le = LabelEncoder()

In [8]:
Data['fruit_name'] = le.fit_transform(Data['fruit_name'])
Data

fruit_label  fruit_name     fruit_subtype  mass  width  height  \
0             1           0      granny_smith   192    8.4     7.3   
1             1           0      granny_smith   180    8.0     6.8   
2             1           0      granny_smith   176    7.4     7.2   
3             2           2          mandarin    86    6.2     4.7   
4             2           2          mandarin    84    6.0     4.6   
5             2           2          mandarin    80    5.8     4.3   
6             2           2          mandarin    80    5.9     4.3   
7             2           2          mandarin    76    5.8     4.0   
8             1           0          braeburn   178    7.1     7.8   
9             1           0          braeburn   172    7.4     7.0   
10            1           0          braeburn   166    6.9     7.3   
11            1           0          braeburn   172    7.1     7.6   
12            1           0          braeburn   154    7.0     7.1   
13            1           0  golden_delicious   164    7.3     7.7   
14            1           0  golden_delicious   152    7.6     7.3   
15            1           0  golden_delicious   156    7.7     7.1   
16            1           0  golden_delicious   156    7.6     7.5   
17            1           0  golden_delicious   168    7.5     7.6   
18            1           0       cripps_pink   162    7.5     7.1   
19            1           0       cripps_pink   162    7.4     7.2   
20            1           0       cripps_pink   160    7.5     7.5   
21            1           0       cripps_pink   156    7.4     7.4   
22            1           0       cripps_pink   140    7.3     7.1   
23            1           0       cripps_pink   170    7.6     7.9   
24            3           3     spanish_jumbo   342    9.0     9.4   
25            3           3     spanish_jumbo   356    9.2     9.2   
26            3           3     spanish_jumbo   362    9.6     9.2   
27            3           3  selected_seconds   204    7.5     9.2   
28            3           3  selected_seconds   140    6.7     7.1   
29            3           3  selected_seconds   160    7.0     7.4   
30            3           3  selected_seconds   158    7.1     7.5   
31            3           3  selected_seconds   210    7.8     8.0   
32            3           3  selected_seconds   164    7.2     7.0   
33            3           3      turkey_navel   190    7.5     8.1   
34            3           3      turkey_navel   142    7.6     7.8   
35            3           3      turkey_navel   150    7.1     7.9   
36            3           3      turkey_navel   160    7.1     7.6   
37            3           3      turkey_navel   154    7.3     7.3   
38            3           3      turkey_navel   158    7.2     7.8   
39            3           3      turkey_navel   144    6.8     7.4   
40            3           3      turkey_navel   154    7.1     7.5   
41            3           3      turkey_navel   180    7.6     8.2   
42            3           3      turkey_navel   154    7.2     7.2   
43            4           1    spanish_belsan   194    7.2    10.3   
44            4           1    spanish_belsan   200    7.3    10.5   
45            4           1    spanish_belsan   186    7.2     9.2   
46            4           1    spanish_belsan   216    7.3    10.2   
47            4           1    spanish_belsan   196    7.3     9.7   
48            4           1    spanish_belsan   174    7.3    10.1   
49            4           1           unknown   132    5.8     8.7   
50            4           1           unknown   130    6.0     8.2   
51            4           1           unknown   116    6.0     7.5   
52            4           1           unknown   118    5.9     8.0   
53            4           1           unknown   120    6.0     8.4   
54            4           1           unknown   116    6.1     8.5   
55            4           1           unknown   116    6.3     7.7   
56            

In [9]:
Data['fruit_subtype'] = le.fit_transform(Data['fruit_subtype'])
Data

fruit_label  fruit_name  fruit_subtype  mass  width  height  color_score
0             1           0              3   192    8.4     7.3         0.55
1             1           0              3   180    8.0     6.8         0.59
2             1           0              3   176    7.4     7.2         0.60
3             2           2              4    86    6.2     4.7         0.80
4             2           2              4    84    6.0     4.6         0.79
5             2           2              4    80    5.8     4.3         0.77
6             2           2              4    80    5.9     4.3         0.81
7             2           2              4    76    5.8     4.0         0.81
8             1           0              0   178    7.1     7.8         0.92
9             1           0              0   172    7.4     7.0         0.89
10            1           0              0   166    6.9     7.3         0.93
11            1           0              0   172    7.1     7.6         0.92
12            1           0              0   154    7.0     7.1         0.88
13            1           0              2   164    7.3     7.7         0.70
14            1           0              2   152    7.6     7.3         0.69
15            1           0              2   156    7.7     7.1         0.69
16            1           0              2   156    7.6     7.5         0.67
17            1           0              2   168    7.5     7.6         0.73
18            1           0              1   162    7.5     7.1         0.83
19            1           0              1   162    7.4     7.2         0.85
20            1           0              1   160    7.5     7.5         0.86
21            1           0              1   156    7.4     7.4         0.84
22            1           0              1   140    7.3     7.1         0.87
23            1           0              1   170    7.6     7.9         0.88
24            3           3              7   342    9.0     9.4         0.75
25            3           3              7   356    9.2     9.2         0.75
26            3           3              7   362    9.6     9.2         0.74
27            3           3              5   204    7.5     9.2         0.77
28            3           3              5   140    6.7     7.1         0.72
29            3           3              5   160    7.0     7.4         0.81
30            3           3              5   158    7.1     7.5         0.79
31            3           3              5   210    7.8     8.0         0.82
32            3           3              5   164    7.2     7.0         0.80
33            3           3              8   190    7.5     8.1         0.74
34            3           3              8   142    7.6     7.8         0.75
35            3           3              8   150    7.1     7.9         0.75
36            3           3              8   160    7.1     7.6         0.76
37            3           3              8   154    7.3     7.3         0.79
38            3           3              8   158    7.2     7.8         0.77
39            3           3              8   144    6.8     7.4         0.75
40            3           3              8   154    7.1     7.5         0.78
41            3           3              8   180    7.6     8.2         0.79
42            3           3              8   154    7.2     7.2         0.82
43            4           1              6   194    7.2    10.3         0.70
44            4           1              6   200    7.3    10.5         0.72
45            4           1              6   186    7.2     9.2         0.72
46            4           1              6   216    7.3    10.2         0.71
47            4           1              6   196    7.3     9.7         0.72
48            4           1              6   174    7.3    10.1         0.72
49            4           1              9   132    5.8     8.7         0.73
50            4           1              9   130    6.0     8.2         0.71


In [10]:
X = Data.drop(['fruit_label'],axis=1)

In [11]:
y = Data.fruit_label

In [12]:
from sklearn.model_selection import train_test_split

In [13]:
x_train,x_test, y_train, y_test=train_test_split(X,y,test_size=0.30)

In [14]:
x_train.head()

fruit_name  fruit_subtype  mass  width  height  color_score
39           3              8   144    6.8     7.4         0.75
52           1              9   118    5.9     8.0         0.72
1            0              3   180    8.0     6.8         0.59
36           3              8   160    7.1     7.6         0.76
22           0              1   140    7.3     7.1         0.87

In [15]:
x_test.head()

fruit_name  fruit_subtype  mass  width  height  color_score
43           1              6   194    7.2    10.3         0.70
6            2              4    80    5.9     4.3         0.81
32           3              5   164    7.2     7.0         0.80
3            2              4    86    6.2     4.7         0.80
26           3              7   362    9.6     9.2         0.74

In [16]:
x_train.shape

(41, 6)

In [17]:
y_train.shape

(41,)

In [18]:
x_test.shape

(18, 6)

In [19]:
from sklearn.svm import SVC
model = SVC(kernel='linear',C=1E10)

In [20]:
model.fit(X,y)

SVC(C=10000000000.0, kernel='linear')

In [21]:
New_prediction = model.predict(x_test)
New_prediction

array([4, 2, 3, 2, 3, 4, 2, 4, 3, 4, 4, 1, 1, 1, 1, 2, 1, 4], dtype=int64)

In [22]:
Comp = pd.DataFrame({'ACTUAL_DATA':y_test,
                    "New_prediction":New_prediction})

In [23]:
Comp

ACTUAL_DATA  New_prediction
43            4               4
6             2               2
32            3               3
3             2               2
26            3               3
49            4               4
4             2               2
44            4               4
34            3               3
55            4               4
51            4               4
13            1               1
19            1               1
15            1               1
10            1               1
5             2               2
11            1               1
45            4               4

In [24]:
Train_Score = model.score(x_train,y_train)*100

In [25]:
Train_Score

100.0

In [26]:
Test_Score = model.score(x_test,y_test)*100
print("Testing Score is {}".format(Test_Score))

Testing Score is 100.0


In [27]:
from sklearn.linear_model import LogisticRegression

In [28]:
Lr = LogisticRegression(solver='newton-cg',C=1.0,max_iter=100)

In [29]:
Lr.fit(x_train,y_train)

LogisticRegression(solver='newton-cg')

In [30]:
y_test

43    4
6     2
32    3
3     2
26    3
49    4
4     2
44    4
34    3
55    4
51    4
13    1
19    1
15    1
10    1
5     2
11    1
45    4
Name: fruit_label, dtype: int64

In [31]:
yhat_prob = Lr.predict_proba(x_test)
yhat_prob

array([[1.95670635e-02, 4.15239148e-12, 4.42978348e-02, 9.36135102e-01],
       [6.24224633e-03, 9.87285605e-01, 6.40675982e-03, 6.53884355e-05],
       [2.44899557e-02, 7.24636285e-09, 9.70034422e-01, 5.47561483e-03],
       [2.68445583e-02, 9.44850298e-01, 2.79344495e-02, 3.70694516e-04],
       [1.91887040e-04, 1.16009399e-32, 9.99023793e-01, 7.84319538e-04],
       [8.19449472e-04, 1.41336435e-05, 1.92728430e-02, 9.79893574e-01],
       [1.62459398e-02, 9.66856254e-01, 1.66751558e-02, 2.22650012e-04],
       [1.70357090e-02, 7.86029890e-13, 4.08917562e-02, 9.42072535e-01],
       [1.97206289e-03, 2.02687172e-06, 9.41497795e-01, 5.65281154e-02],
       [2.78540896e-03, 2.19687165e-03, 6.27480604e-02, 9.32269659e-01],
       [3.00485967e-03, 2.34989805e-03, 7.05900742e-02, 9.24055168e-01],
       [9.76411153e-01, 7.27893210e-09, 6.73559711e-03, 1.68532430e-02],
       [9.94800741e-01, 5.07787566e-09, 2.72394002e-03, 2.47531342e-03],
       [9.85697277e-01, 4.72221932e-08, 6.81058535e

In [32]:
Training_score = Lr.score(x_train,y_train)
Training_score

1.0

In [33]:
New_Predication = Lm_predication=Lr.predict(x_test)

In [34]:
Test_score = Lr.score(x_test,New_Predication)

In [35]:
Test_score

1.0

In [36]:
from sklearn.naive_bayes import BernoulliNB, ComplementNB,MultinomialNB,GaussianNB

In [37]:
Bnb = BernoulliNB()
Cnb = ComplementNB()
Mnb = MultinomialNB()
Gnb = GaussianNB()

In [38]:
Bnb = BernoulliNB()
Cnb = ComplementNB()
Mnb = MultinomialNB()
Gnb = GaussianNB()

In [39]:
Bnb.fit(x_train,y_train)

BernoulliNB()

In [40]:
Bnb.alpha

1.0

In [41]:
Train_Score = Bnb.score(x_train,y_train)
Train_Score

0.7317073170731707

In [42]:
Bnb_new_prediction = Bnb.predict(x_test)
Bnb_new_prediction

array([3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 3, 1, 1, 1, 1, 3, 1, 3], dtype=int64)

In [43]:
Test_Score = Bnb.score(x_test,y_test)

In [44]:
Test_Score

0.4444444444444444

In [45]:
Cnb.fit(x_train,y_train)

ComplementNB()

In [46]:
Cnb.alpha

1.0

In [47]:
Train_Score = Cnb.score(x_train,y_train)
Train_Score

0.8536585365853658

In [48]:
Cnb_new_prediction = Cnb.predict(x_test)

In [49]:
Test_Score = Cnb.score(x_test,y_test)
Test_Score

0.5555555555555556

In [50]:
Mnb.fit(x_train,y_train)

MultinomialNB()

In [51]:
Mnb.alpha

1.0

In [52]:
Train_Score = Mnb.score(x_train,y_train)
Train_Score

0.9024390243902439

In [53]:
Mnb_new_prediction = Mnb.predict(x_test)

In [54]:
Test_Score = Mnb.score(x_test,y_test)
Test_Score

0.6111111111111112

In [55]:
Gnb.fit(x_train,y_train)

GaussianNB()

In [56]:
Train_Score = Gnb.score(x_train,y_train)
Train_Score

1.0

In [57]:
Gnb_new_prediction = Gnb.predict(x_test)

In [58]:
Test_Score = Gnb.score(x_test,y_test)

In [59]:
Test_Score

0.7777777777777778

In [60]:
from sklearn.neighbors import KNeighborsClassifier

In [61]:
Knn = KNeighborsClassifier(n_neighbors=10)

In [62]:
Knn.fit(x_train,y_train)

KNeighborsClassifier(n_neighbors=10)

In [63]:
Train_score = Knn.score(x_train,y_train)
Train_score

0.7317073170731707

In [64]:
Test_score

1.0

In [65]:
Knn_prediction = Knn.predict(x_test)
Knn_prediction

array([1, 4, 1, 4, 3, 4, 4, 1, 3, 4, 4, 1, 1, 1, 1, 4, 1, 1], dtype=int64)

In [66]:
from sklearn import tree
clf = tree.DecisionTreeClassifier()
clf = clf.fit(X, y)
clf

DecisionTreeClassifier()

In [67]:
clf.predict # yes i can play the match

<bound method BaseDecisionTree.predict of DecisionTreeClassifier()>

In [68]:
clf.classes_

array([1, 2, 3, 4], dtype=int64)

In [69]:
clf.n_classes_

4

In [70]:
clf.n_features_

6

In [71]:
clf.score(X,y)

1.0

In [72]:
decision_tree = clf.predict(x_test)
decision_tree

array([4, 2, 3, 2, 3, 4, 2, 4, 3, 4, 4, 1, 1, 1, 1, 2, 1, 4], dtype=int64)

In [73]:
final_pred = (New_prediction+yhat_prob+Bnb_new_prediction+Knn_prediction+decision_tree)/5
final_pred

ValueError: operands could not be broadcast together with shapes (18,) (18,4) 